//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFCWebPanel.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFCSqlEntities : DbContext
    {
        public PFCSqlEntities()
            : base("name=PFCSqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblExtensions> TblExtensions { get; set; }
        public virtual DbSet<TblExtGroup> TblExtGroup { get; set; }
        public virtual DbSet<TblGroups> TblGroups { get; set; }
        public virtual DbSet<TblMainOperator> TblMainOperator { get; set; }
        public virtual DbSet<TblRoles> TblRoles { get; set; }
        public virtual DbSet<TblUsers> TblUsers { get; set; }
    }
}
