//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFCWebPanel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExtGroup
    {
        public int TblExtGrID { get; set; }
        public int TblExtGrGroupID { get; set; }
        public int TblExtGrExtID { get; set; }
        public int TblExtGrRow { get; set; }
    
        public virtual TblExtensions TblExtensions { get; set; }
        public virtual TblGroups TblGroups { get; set; }
    }
}
