//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFCWebPanel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblGroups()
        {
            this.TblExtGroup = new HashSet<TblExtGroup>();
        }
    
        public int TblGrID { get; set; }
        public string TblGrName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblExtGroup> TblExtGroup { get; set; }
    }
}
