//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFCWebPanel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMainOperator
    {
        public int TblMoID { get; set; }
        public int TblMoExtNumber { get; set; }
        public int TblMoDay { get; set; }
    }
}
