//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFCWebPanel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TblRoles TblRoles { get; set; }
    }
}
